In [58]:
import pandas as pd
import numpy as np

zzy = pd.read_excel(r'D:\qq\wd\2630639540\FileRecv\zzy.xlsx')
zzy1 = zzy.iloc[2:]

In [59]:
zzy1.columns = [0,1,2,3,4,5,6,7,8,9]

In [8]:
zzy1

,0,1,2,3,4,5,6,7,8,9
2,22420222111200,062240536,罗慧杰,经济与管理学院,国际经济与贸易,文学与传媒学院,汉语言文学,0122401,NaN,NaN
3,22422801110585,012241016,张立臻,文学与传媒学院,编辑出版学,文学与传媒学院,汉语言文学,0122402,NaN,NaN
4,22421125110149,012240911,江海银,文学与传媒学院,编辑出版学,文学与传媒学院,汉语言文学,0122403,NaN,NaN
5,22422823111671,082240506,宋艳红,外国语学院,商务英语,文学与传媒学院,汉语言文学,0122402,NaN,NaN
6,22353304110421,062240820,林薇,经济与管理学院,旅游管理,文学与传媒学院,汉语言文学,0122405,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
211,22421003110629,172250735,邓子超,林学园艺学院,城乡规划,林学园艺学院,地理科学,1722405,NaN,NaN
212,22432524241276,172240209,康乐,林学园艺学院,园艺,林学园艺学院,地理科学,1722405,NaN,NaN
213,22429401150290,082240501,伍婷,外国语学院,商务英语,林学园艺学院,地理科学,1722405,NaN,NaN
214,22420109150594,172240148,陈子豪,林学园艺学院,林学,林学园艺学院,城乡规划,1722507,NaN,NaN
215,22422802180169,072240229,何帮胜,生物与食品工程学院,生物工程,林学园艺学院,城乡规划,1722507,NaN,NaN

In [11]:
zzy1[3].unique()

array(['经济与管理学院', '文学与传媒学院', '外国语学院', '生物与食品工程学院', '林学园艺学院', '民族学与社会学学院',
       '化学与环境工程学院', '医学部', '智能科学与工程学院', '数学与统计学院', '美术与设计学院', '教师教育学院',
       '音乐舞蹈学院', '马克思主义学院'], dtype=object)

In [14]:
zzy1[8] = [1]*214

<ipython-input-14-8b72659aeb3e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zzy1[8] = [1]*214

In [15]:
zzy1

,0,1,2,3,4,5,6,7,8,9,10
2,22420222111200,062240536,罗慧杰,经济与管理学院,国际经济与贸易,文学与传媒学院,汉语言文学,0122401,1,NaN,1
3,22422801110585,012241016,张立臻,文学与传媒学院,编辑出版学,文学与传媒学院,汉语言文学,0122402,1,NaN,1
4,22421125110149,012240911,江海银,文学与传媒学院,编辑出版学,文学与传媒学院,汉语言文学,0122403,1,NaN,1
5,22422823111671,082240506,宋艳红,外国语学院,商务英语,文学与传媒学院,汉语言文学,0122402,1,NaN,1
6,22353304110421,062240820,林薇,经济与管理学院,旅游管理,文学与传媒学院,汉语言文学,0122405,1,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
211,22421003110629,172250735,邓子超,林学园艺学院,城乡规划,林学园艺学院,地理科学,1722405,1,NaN,1
212,22432524241276,172240209,康乐,林学园艺学院,园艺,林学园艺学院,地理科学,1722405,1,NaN,1
213,22429401150290,082240501,伍婷,外国语学院,商务英语,林学园艺学院,地理科学,1722405,1,NaN,1
214,22420109150594,172240148,陈子豪,林学园艺学院,林学,林学园艺学院,城乡规划,1722507,1,NaN,1
215,22422802180169,072240229,何帮胜,生物与食品工程学院,生物工程,林学园艺学院,城乡规划,1722507,1,NaN,1

In [62]:
# 转出
# 
# zzy2
zzy2 = zzy1[[3,4,8]]
zzy2[3] = zzy2[3].astype("str")
zzy2[4] = zzy2[4].astype("str")

<ipython-input-62-d357b2ca66cd>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zzy2[3] = zzy2[3].astype("str")
<ipython-input-62-d357b2ca66cd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zzy2[4] = zzy2[4].astype("str")

In [32]:
zzy2.dtypes

3    string
4    string
8     int64
dtype: object

In [41]:
zzy3=zzy2.groupby([3,4]).agg( { 8:'count'} )

In [42]:
zzy3

                      8
3         4
化学与环境工程学院 制药工程        5
          化学          3
          化学工程与工艺    18
          环境科学        6
医学部       中医学         2
          中药学         1
          医学影像技术      5
          康复治疗学       5
          护理学         1
外国语学院     商务英语       17
          日语          6
          英语          8
教师教育学院    小学教育        1
数学与统计学院   数学与应用数学     1
          统计学         2
文学与传媒学院   新闻学         3
          编辑出版学       8
智能科学与工程学院 信息安全        2
          智能制造工程      1
          物理学         6
          电气工程及其自动化   2
          计算机科学与技术    1
林学园艺学院    园林          6
          园艺         12
          地理科学        5
          城乡规划        4
          林学         11
民族学与社会学学院 社会学        10
生物与食品工程学院 生物制药        1
          生物工程        9
          生物科学        3
          食品科学与工程     3
经济与管理学院   会计学         3
          国际经济与贸易    13
          旅游管理       20
          经济与金融       5
美术与设计学院   环境设计        1
          美术学         1
          视觉传达设计      1
音乐舞蹈学院    音乐学         1
马克思主义学院   思想政治教育      1

In [44]:
# 转入
zzy4 = zzy1[[5,6,8]]
zzy4[5] = zzy4[5].astype("string")
zzy4[6] = zzy4[6].astype("string")
zzy5 = zzy4.groupby([5, 6]).agg({8: 'count'})

<ipython-input-44-4931fe83d6c0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zzy4[5] = zzy4[5].astype("string")
<ipython-input-44-4931fe83d6c0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zzy4[6] = zzy4[6].astype("string")

In [45]:
zzy5

                      8
5         6
化学与环境工程学院 制药工程        2
          化学          8
          化学工程与工艺     3
医学部       中医学         7
          中药学         3
          临床医学       17
          医学影像技术      6
          康复治疗学       2
          护理学         4
外国语学院     日语          1
          英语         17
教师教育学院    小学教育        5
数学与统计学院   数学与应用数学    14
          统计学         1
文学与传媒学院   新闻学         2
          汉语言文学      23
          编辑出版学       1
智能科学与工程学院 智能制造工程      2
          物理学         1
          电子信息工程      4
          电气工程及其自动化  11
          计算机科学与技术   13
林学园艺学院    园林          2
          地理科学        5
          城乡规划        2
法学院       法学         27
生物与食品工程学院 生物制药        1
          食品科学与工程     2
经济与管理学院   会计学        12
          经济与金融       6
美术与设计学院   美术学         1
          视觉传达设计      2
音乐舞蹈学院    航空服务艺术与管理   1
马克思主义学院   思想政治教育      6

In [50]:
zzy6 = pd.concat([zzy3,zzy5],axis=1)

In [54]:
zzy6.columns = ['转入','转出']

zzy6=zzy6.fillna(0)

In [56]:
zzy6 = zzy6.astype("int64")

In [57]:
zzy6

                     转入  转出
化学与环境工程学院 制药工程        5   2
          化学          3   8
          化学工程与工艺    18   3
          环境科学        6   0
医学部       中医学         2   7
          中药学         1   3
          临床医学        0  17
          医学影像技术      5   6
          康复治疗学       5   2
          护理学         1   4
外国语学院     商务英语       17   0
          日语          6   1
          英语          8  17
教师教育学院    小学教育        1   5
数学与统计学院   数学与应用数学     1  14
          统计学         2   1
文学与传媒学院   新闻学         3   2
          汉语言文学       0  23
          编辑出版学       8   1
智能科学与工程学院 信息安全        2   0
          智能制造工程      1   2
          物理学         6   1
          电子信息工程      0   4
          电气工程及其自动化   2  11
          计算机科学与技术    1  13
林学园艺学院    园林          6   2
          园艺         12   0
          地理科学        5   5
          城乡规划        4   2
          林学         11   0
民族学与社会学学院 社会学        10   0
法学院       法学          0  27
生物与食品工程学院 生物制药        1   1
          生物工程        9   0
          生物科学        3   0
          食品科学与工程     3   2
经济与管理学院   会计学         3  12
          国际经济与贸易    13   0
          旅游管理       20   0
          经济与金融       5   6
美术与设计学院   环境设计        1   0
          美术学         1   1
          视觉传达设计      1   2
音乐舞蹈学院    航空服务艺术与管理   0   1
          音乐学         1   0
马克思主义学院   思想政治教育      1   6